name: Order Placement CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      module:
        description: 'Select the module to run tests for'
        required: true
        default: 'all'
        type: choice
        options: 
          - all
          - orderPlacement
          - users
          - productsHistory

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: List test files
        run: ls tests  # List files in the tests directory for debugging

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.module }}" == "all" ]; then
            npx jest --coverage;  # Run all tests with coverage
          else
            npx jest "tests/${{ github.event.inputs.module }}.test.js" --coverage;  # Run specific module tests
          fi

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Display Coverage Summary
        run: |
          echo "Coverage Summary:"
          cat ./coverage/lcov-report/index.html
